accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("profile", views.view_profile, name="profile"),
]

teamtwo/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("activate/<uidb64>/<token>/", views.activate, name="activate"),
    path("profile", views.view_profile, name="profile"),
    path("delete_ratings/<int:rate_id>", views.delete_ratings, name='delete_ratings'),
    path("edit_ratings/<int:rate_id>", views.edit_ratings, name='edit_ratings'),
]

teamtwo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("naturescall/", include("naturescall.urls", namespace="naturescall")),
    path("admin/", admin.site.urls),
    path("naturescall/accounts/", include("accounts.urls", namespace="accounts")),
    path("naturescall/accounts/", include("django.contrib.auth.urls")),
]

accounts/models.py
# from django.db import models
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profilename = models.CharField(default="naturescall member", max_length=50)
    accessible = models.BooleanField(default=False)
    family_friendly = models.BooleanField(default=False)
    transaction_not_required = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)


# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text="Required")

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "profilename",
            "accessible",
            "family_friendly",
            "transaction_not_required",
        ]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email"]

teamtwo/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile
from naturescall.models import Rating


class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text="Required")

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [
            "profilename",
            "accessible",
            "family_friendly",
            "transaction_not_required",
        ]


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email"]

# form for rating and commenting a restroom
class EditRating(forms.ModelForm):
    class Meta:
        model = Rating
        fields = [
            "rating",
            "headline",
            "comment",
        ]

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from naturescall.models import Rating

# from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from .forms import ProfileUpdateForm, UserUpdateForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = "Activate your Naturescall app account."
            message = render_to_string(
                "accounts/acc_active_email.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )
            to_email = form.cleaned_data.get("email")
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            messages.success(
                request,
                "Please confirm your email address to complete the registration.",
            )
            return HttpResponseRedirect(reverse("naturescall:index"))
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
            return render(request, "accounts/signup.html", {"form": form})
    else:
        form = SignupForm()
        return render(request, "accounts/signup.html", {"form": form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        messages.success(
            request,
            "Thank you for your email confirmation. Now you can login to your account.",
        )
        return HttpResponseRedirect(reverse("naturescall:index"))
    else:
        messages.error(request, "Activation link is invalid!")
        return HttpResponseRedirect(reverse("naturescall:index"))


@login_required
def view_profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            msg = "Your account has been updated!"
            messages.success(request, f"{msg}")
            return HttpResponseRedirect(reverse("naturescall:index"))
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(
            instance=request.user.profile,
            initial={"profilename": request.user.username},
        )
    current_user = request.user
    query_set = Rating.objects.filter(user_id=current_user)
    context = {"u_form": u_form, "p_form": p_form, "ratings": query_set}
    return render(request, "accounts/profile.html", context)

teamtwo/accounts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from naturescall.models import Rating

# from django.contrib.auth import login, authenticate
from .forms import SignupForm
from django.contrib.auth.models import User
from django.urls import reverse
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from .forms import ProfileUpdateForm, UserUpdateForm, EditRating
from django.contrib.auth.decorators import login_required


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            current_site = get_current_site(request)
            mail_subject = "Activate your Naturescall app account."
            message = render_to_string(
                "accounts/acc_active_email.html",
                {
                    "user": user,
                    "domain": current_site.domain,
                    "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                    "token": account_activation_token.make_token(user),
                },
            )
            to_email = form.cleaned_data.get("email")
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            messages.success(
                request,
                "Please confirm your email address to complete the registration.",
            )
            return HttpResponseRedirect(reverse("naturescall:index"))
        else:
            messages.error(request, "Unsuccessful registration. Invalid information.")
            return render(request, "accounts/signup.html", {"form": form})
    else:
        form = SignupForm()
        return render(request, "accounts/signup.html", {"form": form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        # login(request, user)
        messages.success(
            request,
            "Thank you for your email confirmation. Now you can login to your account.",
        )
        return HttpResponseRedirect(reverse("naturescall:index"))
    else:
        messages.error(request, "Activation link is invalid!")
        return HttpResponseRedirect(reverse("naturescall:index"))


@login_required
def view_profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            msg = "Your account has been updated!"
            messages.success(request, f"{msg}")
            return HttpResponseRedirect(reverse("naturescall:index"))
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(
            instance=request.user.profile,
            initial={"profilename": request.user.username},
        )
    current_user = request.user
    query_set = Rating.objects.filter(user_id=current_user)
    context = {"u_form": u_form, "p_form": p_form, "ratings": query_set}
    return render(request, "accounts/profile.html", context)

@login_required
def delete_ratings(request, rate_id):
    querySet = Rating.objects.filter(id = rate_id)
    if not querySet:
        raise Http404("Sorry, the comment does not exist")
    rating_entry = querySet[0]
    if rating_entry.user_id != request.user:
        raise Http404("Sorry, you do not have the right to delete this comment")
    else:
        rating_entry.delete()
        return render(request, "accounts/delete_ratings.html")


@login_required
def edit_ratings(request, rate_id):
    querySet = Rating.objects.filter(id = rate_id)
    if not querySet:
        raise Http404("Sorry, the comment does not exist")
    rating_entry = querySet[0]
    if rating_entry.user_id != request.user:
        raise Http404("Sorry, you do not have the right to edit this comment")

    if request.method == "POST":
        if form.is_valid():
            form.save()



    else:
        form = EditRating()
        context = {
            'form' : form,
            'rate_id' : rate_id
        }
        return render(request, "accounts/edit_ratings.html", context)

teamtwo/accounts/templates/accounts/delete_ratings.html
{% extends  "naturescall/index.html" %}
<!-- no search bar in the add_res page -->
{% block form %}
{% endblock %}

{% block content %}
<p>
  <h4 class="card-text">&nbsp;Your rating & comment is deleted.</span></h4>
</p>
{% endblock %}

teamtwo/accounts/templates/accounts/edit_ratings.html
{% block content %}
	<h2>{{ title }}</h2>
	<form action="" method="POST">
		{%csrf_token%}
		{{form.as_p}}
		<input type= "submit" value = "Submit">
	</form>
{% endblock %}

teamtwo/accounts/templates/accounts/profile.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<title>Naturescal</title>
	</head>
	<body>
		<nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
			{% block home %}
			<a class="navbar-brand" href="/naturescall">Naturescall</a>
			{% endblock %}
		</nav>
		<div class="container">
			{% block content %}
			<h2>User-Profile</h2>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				<fieldset class="form-group">
					{{ u_form.as_p}}
					{{ p_form.as_p}}
				</fieldset>
				<input class="btn btn-primary" type="submit" value="Update">
			</form>
			{% endblock %}
		</div>
		<div class="container">
			<div class="accordion" id="accordionExample">
				<br>
				<h3>Ratings and Reviews</h3>
					{% for rating in ratings %}
					<div class="card">
						<div class="card-header" id="heading-{{rating.pk}}">
							<h2 class="mb-0">
								<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse-{{rating.pk}}" aria-expanded="true" aria-controls="collapse-{{rating.pk}}">
									{{rating.restroom_id}}
								</button>
							</h2>
						</div>

						<div id="collapse-{{rating.pk}}" class="collapse" aria-labelledby="heading-{{rating.pk}}" data-parent="#accordionExample">
							<div class="card-body">
								<li>Rating: {{rating.rating}}</li>
								<li>Headline: {{rating.headline}}</li>
								<li>Comment: {{rating.comment}}</li>
								<li><a href="{% url 'accounts:delete_ratings' rating.id %}">Delete Rating</a></li>
								<li><a href="{% url 'accounts:edit_ratings' rating.id %}">Edit Rating</a></li>
							</div>
						</div>
					</div>
					{% endfor %}
			</div>
		</div>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>