naturescall/urls.py
from django.urls import path, include

# from django.contrib.auth import views as auth_views
from . import views

app_name = "naturescall"
urlpatterns = [
    path("", views.index, name="index"),
    path("search_restroom/", views.search_restroom, name="search_restroom"),
    path("restroom_detail/<int:r_id>", views.restroom_detail, name="restroom_detail"),
    path("add_restroom/<slug:r_id>", views.add_restroom, name="add_restroom"),
    path("filter_restroom/", views.filter_restroom, name="filter_restroom"),
    path("rate_restroom/<int:r_id>", views.rate_restroom, name="rate_restroom"),
]
urlpatterns += [
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("accounts/", include("django.contrib.auth.urls")),
]

teamtwo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("naturescall/", include("naturescall.urls", namespace="naturescall")),
    path("admin/", admin.site.urls),
    path("naturescall/accounts/", include("accounts.urls", namespace="accounts")),
    path("naturescall/accounts/", include("django.contrib.auth.urls")),
]

naturescall/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class Restroom(models.Model):
    """Class to hold restroom entries, including their
    yelp ID, description, and amenities."""

    # Set yelp_id max length to 100 based on this:
    # https://github.com/Yelp/yelp-fusion/issues/183
    yelp_id = models.CharField(max_length=100)
    description = models.TextField(blank=False, null=False)
    last_modified = models.DateTimeField(auto_now_add=True)
    accessible = models.BooleanField(default=False)
    family_friendly = models.BooleanField(default=False)
    transaction_not_required = models.BooleanField(default=False)
    title = models.CharField(blank=False, max_length=255, default="Restroom")
    Subtitle = models.CharField(blank=False, max_length=255, default="Subtitle")

    def __str__(self):
        return f"{self.title[:50]}..."

class Rating(models.Model):
    """Class to hold user-generated ratings, headlines, and comments
    for a given restroom"""

    restroom_id = models.ForeignKey(Restroom, on_delete=models.CASCADE)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(
        default=3, validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    headline = models.TextField(max_length=65)
    comment = models.TextField(max_length=500)

naturescall/forms.py
from django import forms
from .models import Restroom, Rating


class LocationForm(forms.Form):
    location = forms.CharField(widget=forms.TextInput, label="Search Location")


# form for displaying yelp search

# form for adding information about restroom
class AddRestroom(forms.ModelForm):
    title = forms.CharField(
        disabled=False,
        label="Restroom",
        widget=forms.TextInput(attrs={"size": 80, "readonly": True}),
    )
    yelp_id = forms.SlugField(
        disabled=False, widget=forms.HiddenInput()
    )
    description = forms.CharField(widget=forms.TextInput(attrs={"size": 80}))

    class Meta:
        model = Restroom
        fields = [
            "title",
            "yelp_id",
            "description",
            "accessible",
            "family_friendly",
            "transaction_not_required",
        ]

    def clean(self):
        super(AddRestroom, self).clean()
        text = self.cleaned_data.get("description")
        if len(text) < 10:
            self._errors["text"] = self.error_class(
                ["Description Should Contain a minimum of 10 characters"]
            )
        return self.cleaned_data


# form for rating and commenting a restroom
class AddRating(forms.ModelForm):
    headline = forms.CharField(widget=forms.TextInput(attrs={"size": 80}))
    comment = forms.CharField(widget=forms.TextInput(attrs={"size": 80}))

    class Meta:
        model = Rating
        fields = [
            "rating",
            "headline",
            "comment",
        ]

naturescall/views.py
from naturescall.models import Restroom, Rating
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect, Http404

# from .forms import LocationForm
from .forms import AddRestroom, AddRating
import requests
from django.contrib.auth.decorators import login_required
from .filters import RestroomFilter
from django.contrib import messages

# import argparse
# import json
# import sys
# import urllib
# from urllib.error import HTTPError
from urllib.parse import quote

# from urllib.parse import urlencode
import os
from django.urls import reverse

api_key = str(os.getenv("yelp_key"))

API_HOST = "https://api.yelp.com"
SEARCH_PATH = "/v3/businesses/search"
BUSINESS_PATH = "/v3/businesses/"


# The index page
def index(request):
    context = {}
    # form = LocationForm(request.POST or None)
    # context["form"] = form
    return render(request, "naturescall/index.html", context)


# The search page for the user to enter address, search for and
# display the restrooms around the location
def search_restroom(request):
    context = {}
    # form = LocationForm(request.POST or None)
    # location = request.POST["location"]
    if request.POST.get("searched") is not None:
        location = request.POST["searched"]
        tableFilter = RestroomFilter()
        k = search(api_key, '"restroom","food","public"', location, 20)
        data = []
        if not k.get("error"):
            data = k["businesses"]
            # Sort by distance
            data.sort(key=getDistance)
        # Load rating data from our database
        for restroom in data:
            restroom["distance"] = int(restroom["distance"])
            # print(restroom["distance"])
            r_id = restroom["id"]
            querySet = Restroom.objects.filter(yelp_id=r_id)
            if not querySet:
                restroom["our_rating"] = "no rating"
                restroom["db_id"] = ""
            else:
                # restroom["our_rating"] = querySet.values()[0]["rating"]
                restroom["db_id"] = querySet.values()[0]["id"]
                # print(restroom["db_id"])
            addr = str(restroom["location"]["display_address"])
            restroom["addr"] = addr.translate(str.maketrans("", "", "[]'"))
        # context["form"] = form
        context["location"] = location
        context["data"] = data
        context["tableFilter"] = tableFilter
        return render(request, "naturescall/search_restroom.html", context)
    else:
        dbRestroom = Restroom.objects.all()
        tableFilter = RestroomFilter(request.GET, queryset=dbRestroom)
        location = request.GET["filtered"]
        yelp_data = search(api_key, '"restroom","food","public"', location, 20)
        data = []
        data1 = []
        data2 = []
        if not yelp_data.get("error"):
            data1 = yelp_data["businesses"]
            data1.sort(key=getDistance)
        for restroom in data1:
            restroom["distance"] = int(restroom["distance"])
            r_id = restroom["id"]
            querySet = Restroom.objects.filter(yelp_id=r_id)
            if not querySet:
                restroom["our_rating"] = "no rating"
                restroom["db_id"] = ""
            else:
                restroom["db_id"] = querySet.values()[0]["id"]
                restroom["accessible"] = querySet.values()[0]["accessible"]
                restroom["family_friendly"] = querySet.values()[0]["family_friendly"]
                restroom["transaction_not_required"] = querySet.values()[0][
                    "transaction_not_required"
                ]
            addr = str(restroom["location"]["display_address"])
            restroom["addr"] = addr.translate(str.maketrans("", "", "[]'"))
        for obj in tableFilter.qs:
            for restroom in data1:
                if restroom["db_id"] == obj.id:
                    data.append(restroom)
                else:
                    data2.append(restroom)
        context["tableFilter"] = tableFilter
        context["data"] = data
        context["data1"] = data2
        return render(request, "naturescall/filtered_search.html", context)


# Filtered search results-:
def filter_restroom(request):
    dbRestroom = Restroom.objects.all()
    tableFilter = RestroomFilter(request.GET, queryset=dbRestroom)
    location = request.GET["filtered"]
    yelp_data = search(api_key, '"restroom","food","public"', location, 20)
    data = []
    data1 = []
    data2 = []
    if not yelp_data.get("error"):
        data1 = yelp_data["businesses"]
        data1.sort(key=getDistance)
    for restroom in data1:
        restroom["distance"] = int(restroom["distance"])
        r_id = restroom["id"]
        querySet = Restroom.objects.filter(yelp_id=r_id)
        if not querySet:
            restroom["our_rating"] = "no rating"
            restroom["db_id"] = ""
        else:
            restroom["db_id"] = querySet.values()[0]["id"]
            restroom["accessible"] = querySet.values()[0]["accessible"]
            restroom["family_friendly"] = querySet.values()[0]["family_friendly"]
            restroom["transaction_not_required"] = querySet.values()[0][
                "transaction_not_required"
            ]
        addr = str(restroom["location"]["display_address"])
        restroom["addr"] = addr.translate(str.maketrans("", "", "[]'"))

    for obj in tableFilter.qs:
        for restroom in data1:
            if restroom["db_id"] == obj.id:
                data.append(restroom)
            else:
                data2.append(restroom)
    context = {"tableFilter": tableFilter, "data": data, "data1": data2}
    return render(request, "naturescall/filtered_search.html", context)


@login_required(login_url="login")
def rate_restroom(request, r_id):
    """Rate a restroom"""
    current_restroom = get_object_or_404(Restroom, id=r_id)
    current_user = request.user
    if request.method == "POST":
        form = AddRating(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.user_id = current_user
            new_entry.restroom_id = current_restroom
            new_entry.save()
            msg = "Congratulations, Your rating has been saved!"
            messages.success(request, f"{msg}")
            return redirect("naturescall:restroom_detail", r_id=current_restroom.id)
    else:
        # check for redundant rating
        querySet = Rating.objects.filter(restroom_id=r_id, user_id=current_user)
        if querySet:
            msg = "Sorry, You have already rated this restroom!!"
            messages.success(request, f"{msg}")
            return redirect("naturescall:restroom_detail", r_id=current_restroom.id)

    form = AddRating()
    context = {"form": form, "title": current_restroom.title}
    return render(request, "naturescall/rate_restroom.html", context)


# The page for adding new restroom to our database
@login_required(login_url="login")
def add_restroom(request, r_id):
    if request.method == "POST":
        f = AddRestroom(request.POST)
        if f.is_valid():
            post = f.save(commit=False)
            post.save()
            return HttpResponseRedirect(reverse("naturescall:index"))
        else:
            return render(request, "naturescall/add_restroom.html", {"form": f})
    else:
        k = get_business(api_key, r_id)
        if k.get("error"):
            raise Http404("Restroom does not exist")
        context = {}
        name = k["name"]
        title = (
            k["name"] + " " + k["location"]["address1"] + " " + k["location"]["city"]
        )
        form = AddRestroom(initial={"yelp_id": r_id, "title": title})
        context["form"] = form
        context["name"] = name
        return render(request, "naturescall/add_restroom.html", context)


def calculate_rating(r_id):
    querySet = Rating.objects.filter(restroom_id=r_id)
    if querySet:
        average_rating = 0
        for rating in querySet.values():
            average_rating += rating["rating"]
        average_rating = average_rating / len(querySet)
        return round(average_rating, 1)
    else:
        return "N/A"


# The page for showing one restroom details
def restroom_detail(request, r_id):
    """Show a single restroom"""
    querySet = Restroom.objects.filter(id=r_id)
    res = {}
    if querySet:
        yelp_id = querySet.values()[0]["yelp_id"]
        yelp_data = get_business(api_key, yelp_id)
        yelp_data["db_id"] = r_id
        yelp_data["rating"] = calculate_rating(r_id)
        yelp_data["accessible"] = querySet.values()[0]["accessible"]
        yelp_data["family_friendly"] = querySet.values()[0]["family_friendly"]
        yelp_data["transaction_not_required"] = querySet.values()[0][
            "transaction_not_required"
        ]
        yelp_data["subtitle"] = querySet.values()[0]["Subtitle"]
        res["yelp_data"] = yelp_data
        addr = str(yelp_data["location"]["display_address"])
        res["addr"] = addr.translate(str.maketrans("", "", "[]'"))
        res["desc"] = querySet.values()[0]["description"]
    else:
        raise Http404("Restroom does not exist")

    ratings = Rating.objects.filter(restroom_id=r_id)
    context = {"res": res, "ratings": ratings}
    return render(request, "naturescall/restroom_detail.html", context)


# Helper function: make an API request
def request(host, path, api_key, url_params=None):
    url_params = url_params or {}
    url = "{0}{1}".format(host, quote(path.encode("utf8")))
    headers = {
        "Authorization": "Bearer %s" % api_key,
    }
    response = requests.request("GET", url, headers=headers, params=url_params)
    return response.json()


# Helper function: fetch searched data with given parameters - search keywords
# as term, address as loaction, and number of data entries to fetch as num
def search(api_key, term, location, num):
    url_params = {
        "term": term.replace(" ", "+"),

naturescall/templates/naturescall/add_restroom.html
{% extends  "naturescall/index.html" %}
<!-- no search bar in the add_res page -->
{% block form %}
{% endblock %}

{% block content %}
<div class="container">
{#	<h2>You are entering details for restroom {{name}}</h2>#}
	<h2>{{name}}</h2>
	<form action="" method="POST">
		{%csrf_token%}
		{{form.as_p}}
		<input class="btn btn-primary" type= "submit" value = "Submit">
	</form>
</div>
{% endblock %}

naturescall/templates/naturescall/filtered_search.html
{% extends "naturescall/index.html" %}

{% block form %}
<form class="form-inline my-2 my-lg-0" method="POST" action= "/naturescall/search_restroom/">
	{% csrf_token %}
<input class="form-control mr-sm-2" type="search" placeholder="Search Location" name = "searched" required="required">
<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
{% endblock %}

{% block content %}
<div class="container-fluid">
	<p>
	<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Select filters</a>
	</p>
	<div class="collapse" id="collapseExample">
		<div class="card card-body">
			<form class="form-inline my-2 my-lg-0" method="GET" enctype="multipart/form-data">
				{% csrf_token %}
				<fieldset class="form-group">
					<input class="form-control mr-sm-2" type="search" placeholder="Search Location" name = "filtered" required="required">
					{{ tableFilter.form.as_p }}
				</fieldset>
				<button href="{% url 'naturescall:filter_restroom'%}" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			</form>
		</div>
	</div>

</form>
	{% if data %}
	<h4>Please find your filtered search</h4>
	{% for d in data%}
	<div class="card" style="width: 30rem;">
		<img class="card-img-top" src={{d.image_url}} alt="Card image cap" style= "width:100%; height:15vw; object-fit: cover;">
		<div class="card-body">
			<h5 class="card-title">{{d.name}}</h5>
			<p class="card-text">{{d.addr}}</p>
			<p class="card-text" style="color:DodgerBlue;">{{d.distance}} meters away</p>
			<a href="{% url 'naturescall:restroom_detail' d.db_id %}" class="btn btn-success">Show Details</a>
		</div>
	</div>
	{% endfor %}
	{% endif %}
	{% if data1 %}
	<h4> Unfiltered Result </h4>
	{% for d in data1%}
	<div class="card" style="width: 30rem;">
		<img class="card-img-top" src={{d.image_url}} alt="Card image cap" style= "width:100%; height:15vw; object-fit: cover;">
		<div class="card-body">
			<h5 class="card-title">{{d.name}}</h5>
			<p class="card-text">{{d.addr}}</p>
			<p class="card-text" style="color:DodgerBlue;">{{d.distance}} meters away</p>
			{% if d.db_id %}
			<a href="{% url 'naturescall:restroom_detail' d.db_id %}" class="btn btn-success">Show Details</a>
			{% else %}
			<a href="{% url 'naturescall:add_restroom' d.id %}" class="btn btn-info">Add Restroom</a>
			{% endif %}
		</div>
	</div>
	{% endfor %}
	{% else %}
	<h3>Location Not Found</h3>
	{% endif %}
</div>
{% endblock %}

naturescall/templates/naturescall/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		<title>Naturescall</title>
	</head>
	<body>
		<!-- navbar -->
		<nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
			{% block home %}
			<a class="navbar-brand" href="/naturescall">Naturescall</a>
			{% endblock %}
		  <ul class="navbar-nav mr-auto">
				{%if not user.is_authenticated %}
		    <li class="nav-item">
		    	<a class="nav-link" href="{% url 'naturescall:accounts:signup'%}" style="color:#2cdf33;">SignUp</a>
		    </li>
		    <li class="nav-item">
		    	<a class="nav-link" href="{% url 'login'%}" style="color:#2cdf33;">Login</a>
		    </li>
				{%else%}
				<!--
				<li class="nav-item">
					<a class="navbar-text" style="color:white;">Hi, {{user}}</a>
				</li>
				-->
				<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" style="color:white;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">Hi, {{user}}</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'naturescall:accounts:profile'%}">Profile</a>
        </div>
      </li>
				<li class="nav-item">
					<a class="nav-link" href="{%url 'logout'%}" style="color:DodgerBlue;">Logout</a>
				</li>
				{%endif%}
		  </ul>

			<!-- search form -->
			{% block form %}
			<form class="form-inline my-2 my-lg-0" method="POST" action= "search_restroom/">
				{% csrf_token %}
      <input class="form-control mr-sm-2" type="search" placeholder="Search Location" name = "searched" required="required">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    	</form>
			{% endblock %}
		</nav>

		{% block content %}
		<div class="container">
			<div class="jumbotron bg-success text-white" >
				<h1>Welcome to Nature's call</h1>
				{% if messages %}
				<ul class="messages">
					{% for message in messages %}
					<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
					{% endfor %}
				</ul>
			</div>
		</div>
		{% endif %}
		{% endblock %}


		<!-- bootstrap js scripts -->
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	</body>
</html>

naturescall/templates/naturescall/rate_restroom.html
{% extends  "naturescall/index.html" %}
<!-- no search bar in the add_res page -->
{% block form %}
{% endblock %}

{% block content %}
<div class="container">
	<h2>{{ title }}</h2>
	<form action="" method="POST">
		{%csrf_token%}
		{{form.as_p}}
		<input class="btn btn-primary" type= "submit" value = "Submit">
	</form>
</div>
{% endblock %}

naturescall/templates/naturescall/restroom_detail.html
{% extends "naturescall/search_restroom.html" %}
{% block home %}
<a class="navbar-brand" href="/naturescall">Nature's Call</a>
{% endblock %}


{% block form %}
<form class="form-inline my-2 my-lg-0" method="POST" action= "/naturescall/search_restroom/">
  {% csrf_token %}
<input class="form-control mr-sm-2" type="search" placeholder="Search Location" name = "searched" required="required">
<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
{% endblock %}

{% block content %}


<div class="container-fluid">
      <img class="img-fluid" src={{res.yelp_data.image_url}} alt="Card image cap" style= "width:100%; height:15vw; object-fit: cover;">
</div>

<div class="container"
  <div class="col d-flex justify-content-center">

    {% if messages %}
    <div class="alert alert-success" role="alert">
      <ul class="messages">
        {% for message in messages %}
        <h4{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</h4>
        {% endfor %}
      </ul>
    </div>
    {% endif %}


    <div class="card">
      <div class="card-body">
        <h2 class="card-title">
          {{res.yelp_data.name}}
          {% if res.yelp_data.accessible %}
          <span class="badge badge-secondary bg-success text-white">Accessible</span>
          {% endif %}
          {% if res.yelp_data.family_friendly  %}
          <span class="badge badge-secondary bg-primary text-white" >Family Friendly</span>
          {% endif %}
          {% if res.yelp_data.transaction_not_required  %}
          <span class="badge badge-secondary bg-warning text-dark">Transaction Not Required</span>
          {% endif %}
        </h2>
        <h4 class="card-text"> Address: {{res.addr}}</h4>
        <h4 class="card-text">Rating: {{res.yelp_data.rating}} </h4>
        <h4 class="card-text">Description: {{res.desc}} </h4>
        <h4 class="card-text">Subtitle: {{res.yelp_data.subtitle}} </h4>
        <a href="{% url 'naturescall:rate_restroom' res.yelp_data.db_id %}" class="btn btn-primary">Rate Now!</a>
      </div>
    </div>
  </div>
</div>
<br>
<div class="container">
  <div class="card">
    <div class="card-body">
      <h2 class="card-title">Ratings</h2>
      {% for rating in ratings %}
        <h4>{{rating.user_id}}</h4>
        Rating: {{rating.rating}}<br>
        Headline: {{rating.headline}}<br>
        Comment: {{rating.comment}}<br>
        <br>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

naturescall/templates/naturescall/search_restroom.html
{% extends "naturescall/index.html" %}

{% block home %}
<a class="navbar-brand" href="/naturescall">Naturescall</a>
{% endblock %}

{% block form %}
<form class="form-inline my-2 my-lg-0" method="POST" action= "/naturescall/search_restroom/">
	{% csrf_token %}
<input class="form-control mr-sm-2" type="search" placeholder="Search Location" name = "searched" required="required">
<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
</form>
{% endblock %}

{% block content %}
<div class="container-fluid">
	<p>
	<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">Select filters</a>
	</p>
	<div class="collapse" id="collapseExample">
		     <div class="card card-body">
			     <form class="form-inline my-2 my-lg-0" method="GET" enctype="multipart/form-data">
				     {% csrf_token %}
				     <fieldset class="form-group">
				<input class="form-control mr-sm-2" type="search" placeholder="Search Location" name = "filtered" required="required">
				      {{tableFilter.form.as_p}}
				       </fieldset>
				       <button href="{% url 'naturescall:filter_restroom'%}" class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
			     </form>
		     </div>
			    </div>

      {% if data %}
        {% for d in data%}
        <div class="card" style="width: 30rem;">
          <img class="card-img-top" src={{d.image_url}} alt="Card image cap" style= "width:100%; height:15vw; object-fit: cover;">
          <div class="card-body">
            <h5 class="card-title">{{d.name}}</h5>
            <p class="card-text">{{d.addr}}</p>
            <p class="card-text" style="color:DodgerBlue;">{{d.distance}} meters away</p>
            {% if d.db_id %}
              <!--<p class="card-text">our rating: {{d.our_rating}}</p>-->
              <a href="{% url 'naturescall:restroom_detail' d.db_id %}" class="btn btn-success">Show Details</a>
            {% else %}
              <a href="{% url 'naturescall:add_restroom' d.id %}" class="btn btn-info">Add Restroom</a>
            {% endif %}
          </div>
        </div>
        {% endfor %}
        {% else %}
            <h3>Location Not Found</h3>
        {% endif %}
    </div>
{% endblock %}

    <!--
    <br>
    <div class="container">
    {% if data %}
        <h2>You are searching for restrooms near {{ location }}</h2>
        <table width="900", border="1">
            <tr>
                <th><label for='yelp_id'><h3>YelpBusinessID</h3></label></th>
                <th><label for='restroom'><h3> Restroom</h3></label></th>
                <th><label for='address'><h3>Address</h3></label></th>
                <th><label for='distance'><h3> Distance(meters)</h3></label></th>
                <th><label for='rating'><h3>OurRating</h3></label></th>
            </tr>
            {% for d in data%}
                <tr>
                    <td align='right'> {{ d.id }} </td>
                    <td align='right'>
                        {% if d.db_id %}
                            <a href ="{% url 'naturescall:restroom_detail' d.db_id %}">{{ d.name }}</a>&emsp;
                        {% else %}
                            {{ d.name }}
                        {% endif %}
                    </td>
                    <td align='right'>{{ d.addr }} </td>
                    <td align='right'>{{ d.distance }} </td>
                    <td align='center'>
                        {% if not d.db_id %}
                            <a href= "{% url 'naturescall:add_restroom' d.id %}">Add Restroom</a>
                        {% else %}
                            {{ d.our_rating }}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <h3>Location Not Found</h3>
    {% endif %}
    </div>
    -->